services:
  postgres:
    image: postgres:17
    container_name: clothestore-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clothestore
      POSTGRES_PASSWORD: clothestore
      POSTGRES_DB: clothestore
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: